AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Resources:
  MyLambdaFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: api_publico.lambda_handler
      Runtime: python3.8
      CodeUri: ./app
      Description: 'Lambda function'

      Events:
        GetHello:
          Type: Api
          Properties:
            Path: /hello
            Method: GET